// src/pages/api/v1/tasks/list.ts

import { NextApiRequest, NextApiResponse } from 'next'
import { TaskInfo } from '../../../../types/routine'

export default function handler(
    req: NextApiRequest,
    res: NextApiResponse<Object>
) {
    const mockData: TaskInfo[] = [
        {
            taskId: 1,
            writer: 'Grace',
            title: 'Work on project',
            memo: 'Coding and debugging',
            startAt: '2023-04-25 09:00:00',
            endAt: '2023-04-26 12:00:00',
            isFinished: false,
            sharedMembersNicknameList: [],
        },
        {
            taskId: 2,
            writer: 'John',
            title: 'Prepare presentation',
            memo: 'Create slides and rehearse',
            startAt: '2023-04-25 14:00:00',
            endAt: '2023-04-26 17:00:00',
            isFinished: true,
            sharedMembersNicknameList: ['Jane'],
        },
        {
            taskId: 3,
            writer: 'Alice',
            title: 'Review proposal',
            memo: 'Provide feedback on proposal',
            startAt: '2023-04-26 10:00:00',
            endAt: '2023-04-26 12:00:00',
            isFinished: true,
            sharedMembersNicknameList: ['Bob', 'Charlie'],
        },
        {
            taskId: 4,
            writer: 'David',
            title: 'Meeting with client',
            memo: 'Discuss project requirements',
            startAt: '2023-04-26 14:00:00',
            endAt: '2023-04-26 15:30:00',
            isFinished: true,
            sharedMembersNicknameList: [],
        },
        {
            taskId: 5,
            writer: 'Grace',
            title: 'Update documentation',
            memo: 'Add new features to documentation',
            startAt: '2023-04-27 09:00:00',
            endAt: '2023-04-27 12:00:00',
            isFinished: false,
            sharedMembersNicknameList: ['John'],
        },
        {
            taskId: 6,
            writer: 'Alice',
            title: 'Code review',
            memo: 'Review code changes and provide feedback',
            startAt: '2023-04-27 14:00:00',
            endAt: '2023-04-27 16:00:00',
            isFinished: false,
            sharedMembersNicknameList: ['Bob', 'Charlie'],
        },
        {
            taskId: 7,
            writer: 'Bob',
            title: 'Testing',
            memo: 'Test new features and report issues',
            startAt: '2023-04-28 10:00:00',
            endAt: '2023-04-28 12:00:00',
            isFinished: false,
            sharedMembersNicknameList: ['Alice', 'David'],
        },
        {
            taskId: 8,
            writer: 'John',
            title: 'Meet with stakeholders',
            memo: 'Discuss project progress and next steps',
            startAt: '2023-04-28 14:00:00',
            endAt: '2023-04-28 15:30:00',
            isFinished: false,
            sharedMembersNicknameList: ['Grace'],
        },
        {
            taskId: 9,
            writer: 'Charlie',
            title: 'Documentation review',
            memo: 'Review and edit documentation',
            startAt: '2023-04-29 10:00:00',
            endAt: '2023-04-29 12:00:00',
            isFinished: false,
            sharedMembersNicknameList: ['Bob', 'David'],
        },
        {
            taskId: 10,
            writer: 'Grace',
            title: 'Debugging',
            memo: 'Fix bugs in code',
            startAt: '2023-04-30 09:00:00',
            endAt: '2023-04-30 12:00:00',
            isFinished: false,
            sharedMembersNicknameList: ['John', 'Alice'],
        },
        {
            taskId: 11,
            writer: 'Bob',
            title: 'Planning meeting',
            memo: 'Discuss project plan and roadmap',
            startAt: '2023-04-30 14:00:00',
            endAt: '2023-04-30 15:30:00',
            isFinished: false,
            sharedMembersNicknameList: [],
        },
        {
            taskId: 12,
            writer: 'Alice',
            title: 'Implement new feature',
            memo: 'Add new functionality to project',
            startAt: '2023-05-01 10:00:00',
            endAt: '2023-05-01 13:00:00',
            isFinished: false,
            sharedMembersNicknameList: ['Charlie', 'David'],
        },
        {
            taskId: 13,
            writer: 'John',
            title: 'Client presentation',
            memo: 'Present project progress to client',
            startAt: '2023-05-01 15:00:00',
            endAt: '2023-05-01 17:00:00',
            isFinished: false,
            sharedMembersNicknameList: ['Grace'],
        },
        {
            taskId: 14,
            writer: 'David',
            title: 'Code optimization',
            memo: 'Optimize code performance',
            startAt: '2023-05-02 10:00:00',
            endAt: '2023-05-02 12:00:00',
            isFinished: false,
            sharedMembersNicknameList: [],
        },
        {
            taskId: 15,
            writer: 'Charlie',
            title: 'Testing',
            memo: 'Test new functionality and report issues',
            startAt: '2023-05-02 14:00:00',
            endAt: '2023-05-02 16:00:00',
            isFinished: false,
            sharedMembersNicknameList: ['Bob', 'Alice'],
        },
        {
            taskId: 16,
            writer: 'Grace',
            title: 'Documentation',
            memo: 'Update project documentation',
            startAt: '2023-05-03 09:00:00',
            endAt: '2023-05-03 12:00:00',
            isFinished: false,
            sharedMembersNicknameList: ['John'],
        },
        {
            taskId: 17,
            writer: 'Bob',
            title: 'Code review',
            memo: 'Review code changes and provide feedback',
            startAt: '2023-05-03 14:00:00',
            endAt: '2023-05-03 16:00:00',
            isFinished: false,
            sharedMembersNicknameList: ['Alice', 'David'],
        },
        {
            taskId: 18,
            writer: 'Alice',
            title: 'Debugging',
            memo: 'Fix bugs in code',
            startAt: '2023-05-04 10:00:00',
            endAt: '2023-05-04 12:00:00',
            isFinished: false,
            sharedMembersNicknameList: ['Charlie', 'Grace'],
        },
        {
            taskId: 19,
            writer: 'David',
            title: 'Meeting with stakeholders',
            memo: 'Discuss project progress and next steps',
            startAt: '2023-05-04 14:00:00',
            endAt: '2023-05-04 15:30:00',
            isFinished: false,
            sharedMembersNicknameList: ['John'],
        },
        {
            taskId: 20,
            writer: 'John',
            title: 'Project review',
            memo: 'Evaluate project performance and outcomes',
            startAt: '2023-05-05 10:00:00',
            endAt: '2023-05-05 12:00:00',
            isFinished: false,
            sharedMembersNicknameList: [
                'Bob',
                'Charlie',
                'Alice',
                'David',
                'Grace',
            ],
        },
    ]
    return res.status(200).json(mockData)
}
